### PR TITLE
Change pin arguments to 16 bits from at for 32 bit uC compatibility 

### PR DESCRIPTION
**Pull request by mikeshub**
There really isn't much to say about this PR. I have setup a 3d printer using the LPC1768 microcontroller using Marlin. Marlin uses this code for the Neopixels. It doesn't work with the pin being an 8 bit value. So this changes them to 16 bit values.

### CODE REVIEW

**Comment by ladyada** [comment]
hiya thank u - please make adjustments so travis.ci passes :)

**Comment by mikeshub** [comment]
That got it.

**Comment by mikeshub** [comment]
Discussion over at Marlin on this:

https://github.com/MarlinFirmware/Marlin/issues/14754

**Comment by PaintYourDragon** [comment]
If I were feeling more uptight I’d suggest a NeoPixel_pin_t typedef (with #ifdef(s) for different architectures) to minimize the cognitive load on something like an ATtiny. But it’s 2019 and c’mon, ATtiny, really? This is fine as-is and I will merge.

**Comment by p3p** [comment]
Ah well guess my LPC176x support got in by the backdoor was trying to keep it separate until the LPC176x Arduino framework was a little more stable and Arduino compatible.

**Comment by mikeshub** [comment]
Seems to me that Marlin is bridging the gap between Arduino and mBed (ARMduino?). Hopefully some of the Marlin effort will get picked up by Arduino for even more hardware support. Thanks for adding this in.

I'll be happy to add the pin type def. Do you think an #ifdef __AVR_ATtiny85__ would be the right preprocessor check for ATTiny or is there a better define?

Would it make sense to just go ahead and change the type to signed for the pins since in the class the pin is assigned to a signed variable? Or would it make more sense to do something like NeoPixel_pin_t and NeoPixel_upin_t for the signed vs unsigned?

**Comment by ladyada** [comment]
no need to adapt this, the attiny will just have to cope with the extra bytes of ram used - thats ok

**Comment by mikeshub** [comment]
You say that now, just you wait until this ruins someones gadget! :)

**Pull request merged**
